version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pROgY547Ge221
      POSTGRES_DB: iq-testonline
      POSTGRES_USER: Premiumadsselected
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432